[jnyz-app/server]2024/03/24 - 12:05:41.403	[31merror[0m	/root/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/24 - 12:10:53.973	[31merror[0m	/root/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:8888: use of closed network connection
[jnyz-app/server]2024/03/24 - 12:11:13.916	[31merror[0m	/root/repo/jnyz-app/server/core/server.go:54	net.Listen error: listen tcp :8888: bind: address already in use
[jnyz-app/server]2024/03/24 - 12:16:13.783	[31merror[0m	/root/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/24 - 21:27:47.660	[31merror[0m	/home/amos/repo/jnyz-app/server/api/v1/system/sys_initdb.go:35	Ëá™Âä®ÂàõÂª∫Êï∞ÊçÆÂ∫ìÂ§±Ë¥•!	{"error": "dial tcp: lookup mariadb on 127.0.0.53:53: server misbehaving"}
[jnyz-app/server]2024/03/24 - 21:28:07.461	[31merror[0m	/home/amos/repo/jnyz-app/server/api/v1/system/sys_initdb.go:35	Ëá™Âä®ÂàõÂª∫Êï∞ÊçÆÂ∫ìÂ§±Ë¥•!	{"error": "Casbin Ë°® (casbin_rule) Êï∞ÊçÆÂàùÂßãÂåñÂ§±Ë¥•!: Error 1062 (23000): Duplicate entry 'p-100-/user/admin_register-POST---' for key 'idx_casbin_rule'", "errorVerbose": "Error 1062 (23000): Duplicate entry 'p-100-/user/admin_register-POST---' for key 'idx_casbin_rule'\nCasbin Ë°® (casbin_rule) Êï∞ÊçÆÂàùÂßãÂåñÂ§±Ë¥•!\njnyz-app/server/source/system.(*initCasbin).InitializeData\n\t/home/amos/repo/jnyz-app/server/source/system/casbin.go:174\njnyz-app/server/service/system.MysqlInitHandler.InitData\n\t/home/amos/repo/jnyz-app/server/service/system/sys_initdb_mysql.go:88\njnyz-app/server/service/system.(*InitDBService).InitDB\n\t/home/amos/repo/jnyz-app/server/service/system/sys_initdb.go:125\njnyz-app/server/api/v1/system.(*DBApi).InitDB\n\t/home/amos/repo/jnyz-app/server/api/v1/system/sys_initdb.go:34\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2938\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2009\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"}
[jnyz-app/server]2024/03/24 - 21:29:09.038	[31merror[0m	/home/amos/repo/jnyz-app/server/api/v1/system/sys_initdb.go:24	Â∑≤Â≠òÂú®Êï∞ÊçÆÂ∫ìÈÖçÁΩÆ!
[jnyz-app/server]2024/03/24 - 21:29:21.594	[31merror[0m	/home/amos/repo/jnyz-app/server/api/v1/system/sys_initdb.go:24	Â∑≤Â≠òÂú®Êï∞ÊçÆÂ∫ìÈÖçÁΩÆ!
[jnyz-app/server]2024/03/24 - 21:29:55.773	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/24 - 21:33:50.765	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/24 - 21:36:49.544	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/24 - 21:37:05.018	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/24 - 21:41:16.990	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/24 - 21:42:06.920	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/24 - 21:44:52.454	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/24 - 21:45:26.991	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/24 - 22:38:37.334	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
